### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by lougroshek** [Hyperobjekt/ddk-map#1]
Map needs to accept additional routing settings in the hash for: 

- [x] Active shape type (at present only one option for census tract)
- [x] Year of data displayed (2010 or 2015)
- [ ] Zoomed metro location (using `msaid15` for each metro area), will be blank if no metro location is zoomed - the data pipeline will produce a list of metro areas against which this can be validated. It resides [here](https://ddk-source.s3.amazonaws.com/proc/1.0.0/helpers/metros.json) and [here](https://ddk-source.s3.amazonaws.com/proc/1.0.0/helpers/metros.csv).
- [ ] Child opportunity score vs opportunity level (`coi`vs`ol`) - This is going to be an extremely long list. We can probably add a script to generate it to the data pipeline, and they will also be in the dictionary. Which resides [here](https://ddk-source.s3.amazonaws.com/proc/1.0.0/helpers/dictionary.csv), [here](https://ddk-source.s3.amazonaws.com/proc/1.0.0/helpers/dictionary.json), and [here](https://ddk-source.s3.amazonaws.com/proc/1.0.0/helpers/en_US.json).
- [x] Data normalization level ('m' for metro, 'n' for national)
- [x] Version of map tileset data 
- [ ] years of data to load, could be 2010, 2015, or both

## Tasks

- [ ] Accept and validate the values in the routing app
- [ ] Create new state nodes in the state management object for all of these values
- [ ] Set the state from the hash for all of these new values
- [ ] Verify that they are all being set correctly from both the hash and localStorage

Both setting state from local storage and from hash need to accommodate these new settings.

**Comment by hoshmn** [comment]
@lougroshek just to be sure I understand, there should be a separate setting for year_display as year_load? when will these not match?

**Comment by lougroshek** [comment]
@hoshmn It seems counterintuitive, but the client has requested the ability to limit the data loaded to one or the other year. Though we aren't building separate tilesets for the separate years at present, they want that option. Year display, on the other hand, corresponds to a selected year, the year of data currently displayed in the map, and there is a control in the UI for it. In the case where we load both 2010 and 2015 data (which for the present time will be all cases), the map state will need to know which of those to display. If the data loaded is for just 2010 or just 2015, the year selection control won't need to be displayed, but in order to accommodate all possible use cases we can't combine these two variables.
