### ISSUE TITLE
Add font sets to project

### ISSUE THREAD

**Issue by lougroshek** [Hyperobjekt/ddk-map#22]
Add required font sets to project. 

## Fonts to add:

- https://fonts.google.com/specimen/Fira+Sans
- https://fonts.google.com/specimen/Merriweather

## Potential resource

- https://blog.logrocket.com/3-ways-to-add-custom-fonts-to-your-material-ui-project/

## Tasks

- [x] Investigate options that work best with Material UI
- [x] I think we should probably rule out https://github.com/fontsource/fontsource as a first option since both fonts in the wireframes are both Google fonts. 
- [x] Add font sets
