### ISSUE TITLE
Add link to citation info in Mapbox attribution section

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/ddk-map#77]
Add a link to citation info in map, in the Mapbox attribution section (lower left of map). Clicking this should take users to the relevant FAQ item, which needs to be created:

> How should I cite this resource?
> 
> For social media and web-based uses, you can link directly to this website: diversitydatakids.org/maps. 
> For non-web based uses (reports, presentations, etc.), please use the following citation: diversitydatakids.org. 2021. Institute for Child, Youth and Family Policy, Heller School for Social Policy and Management, Brandeis University.Waltham, MA.

# Tasks

- [ ] Add link in bottom left of map that reads "Citation info"
- [ ] Add the item above to the FAQs (as last entry)
- [ ] Clicking link should open the FAQ item 
- [ ] Submit PR for internal review
- [ ] Share with client

**Comment by achlong** [comment]
Can put placeholder copy if necessary
